version: '3.0'
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
   - 8000:8000
  image: app:django
  container_name: django_container
  command: python manage.py runserver 0.0.0.0:8000
  depends_on:
   - db
 db:
  image: mariadb
  environment:
   - MYSQL_DATABASE=mariadb
   - MYSQL_ROOT_PASSWORD=mariadb
   - MYSQL_USER=mariadb
   - MYSQL_PASSWORD=mariadb
  volumes:
   - ./mariadb_data/db:/var/lib/mysql
  ports:
      - "3308:3306"
 web:
    build: '.'
    ports:
      - '5000:5000'
